In [1]:
import random

In [ ]:
schools = ['Eastern Alamance High School','Orange High School','Rockingham County High']
grades = [9,10,11,12]
student_names = ['JOEY SANCHEZ','JAY GARCIA','JEFF LAMORT','TOM GANDY','BARBARA GUTSTADT','NATE DILGER','ELEANOR COLEMAN','RANDY FOLK','MARTIN BURKE','JEREMY MANGINE','RAYMOND SCRUGGS','MIKE RUSSELL','MALIA SAMSON','JOANNE KOOL','GAIL WEISS','TAD HOLLEY','CORLETTE FAULK','TIM COXON','JEFF CLARK','MICHELE STEPANEK','GREG WOOD','JILLES VAN OORT','DEREK BAER','CHRIS MOFFAT','MICHAEL LENIHAN','JEFF KAMP','JOHN BACHYNSKI','KIMBERLY MOORE','ALEX BROWN','RYAN HENDERSON','HAO LIU','EVA CHAFFIN','ASTRID KOHLWES','AMY MCGOWEN','JOE WOLSTENCROFT PHD','MELISSA WHITE','MARTIN PALUCH','CHRIS TAYLOR','JEAN-SEBASTIEN LEGARE','TCC LAST','ANTOINE MONSTIER','GARY LORFANO','MAT SHERWOOD','TIMOTHY RYKACZEWSKI','JORGE ARTETA','JENNA CRAVEN','YOLANDA JAKUBOWSKI','BOB BRANCATO','JANE GANNON','CRAIG HUNTER','TS BREYER','JOHN GARDNER','LISA DEPAULO','DAVID BROCK','DEAN LONDO','SEAN BUSCA','PETER MURPHY','MARIETJIE DU PLESSIS','DANIEL ROONEY','JASON DICK','TA LAST','RYAN PRITCHARD','ERIC SUKHENKO','STEPHANIE CHIQUILLO','ROBERT DEVITZ','TKC AIMES','JEAN FRANCOIS MARINIER','CHRIS HAGARTY','LYNN BLAKE','MIKE SMITH','PATRICIA CAMERON','NICHOLAS ELLISON','MN GRAND','CAROL DISLER','RITA REASONS','HUAN NGUYEN','TATSURO OSHIMOTO','BARRY COLFLESH','CINDY CHACE','JOE FALARDEAU','MARCUS YADO','JEFF BABINEAU','JIM WHELAN','JIM TONORE','ABBY CHEN','MANWAH HO','RICK KELLY','SYLVAIN RABY','JEREMY CHEN','DEBRA COTELA','PR LAST','RICHARD MAYCHRICH','ANNA BROWE','JACLYN BEAUDREAU - CUMMINGS','DUSTIN RALSTON','CATHY CURTIS-WHITE','DICK SHURTS','JOHN REHUS','BEN JAMES','ANDREW SZUNYOG','DANIEL DIAS','PETER SMITH','RICK BURR','GREGORY RICHARDSON','MAXIME POUCHET','MICHAEL ABRAHAM','CHARLES ZHANG','ANDREW TOBEY','PAIGE PEREZ','JESSICA MIREAULT','VAL PATARINI','HEBE CONG','FUYUKA TSURUDA','JAMES HARRIS','JOHN C. HAMMER','PETER SMITH']
teacher_names =

In [9]:
count = 1
for i in student_names:
    school = schools[random.randint(0,len(schools)-1)]
    grade = grades[random.randint(0,len(grades)-1)]
    print("student{0} = Student(student_id={1}, school='{2}', grade_level={3}, name ='{4}')".format(count,count,school,grade,i))
    count += 1

student1 = Student(student_id=1, school='Orange High School', grade_level=9, name ='JOEY SANCHEZ')
student2 = Student(student_id=2, school='Rockingham County High', grade_level=9, name ='JAY GARCIA')
student3 = Student(student_id=3, school='Eastern Alamance High School', grade_level=12, name ='JEFF LAMORT')
student4 = Student(student_id=4, school='Orange High School', grade_level=11, name ='TOM GANDY')
student5 = Student(student_id=5, school='Orange High School', grade_level=12, name ='BARBARA GUTSTADT')
student6 = Student(student_id=6, school='Rockingham County High', grade_level=12, name ='NATE DILGER')
student7 = Student(student_id=7, school='Orange High School', grade_level=10, name ='ELEANOR COLEMAN')
student8 = Student(student_id=8, school='Rockingham County High', grade_level=12, name ='RANDY FOLK')
student9 = Student(student_id=9, school='Eastern Alamance High School', grade_level=9, name ='MARTIN BURKE')
student10 = Student(student_id=10, school='Eastern Alamance High School', grade_level=11, name ='JEREMY MANGINE')
student11 = Student(student_id=11, school='Orange High School', grade_level=12, name ='RAYMOND SCRUGGS')
student12 = Student(student_id=12, school='Rockingham County High', grade_level=9, name ='MIKE RUSSELL')
student13 = Student(student_id=13, school='Rockingham County High', grade_level=11, name ='MALIA SAMSON')
student14 = Student(student_id=14, school='Eastern Alamance High School', grade_level=9, name ='JOANNE KOOL')
student15 = Student(student_id=15, school='Orange High School', grade_level=10, name ='GAIL WEISS')
student16 = Student(student_id=16, school='Orange High School', grade_level=12, name ='TAD HOLLEY')
student17 = Student(student_id=17, school='Rockingham County High', grade_level=10, name ='CORLETTE FAULK')
student18 = Student(student_id=18, school='Orange High School', grade_level=10, name ='TIM COXON')
student19 = Student(student_id=19, school='Orange High School', grade_level=9, name ='JEFF CLARK')
student20 = Student(student_id=20, school='Eastern Alamance High School', grade_level=11, name ='MICHELE STEPANEK')
student21 = Student(student_id=21, school='Eastern Alamance High School', grade_level=10, name ='GREG WOOD')
student22 = Student(student_id=22, school='Orange High School', grade_level=12, name ='JILLES VAN OORT')
student23 = Student(student_id=23, school='Orange High School', grade_level=11, name ='DEREK BAER')
student24 = Student(student_id=24, school='Rockingham County High', grade_level=9, name ='CHRIS MOFFAT')
student25 = Student(student_id=25, school='Rockingham County High', grade_level=12, name ='MICHAEL LENIHAN')
student26 = Student(student_id=26, school='Orange High School', grade_level=12, name ='JEFF KAMP')
student27 = Student(student_id=27, school='Eastern Alamance High School', grade_level=9, name ='JOHN BACHYNSKI')
student28 = Student(student_id=28, school='Rockingham County High', grade_level=9, name ='KIMBERLY MOORE')
student29 = Student(student_id=29, school='Rockingham County High', grade_level=11, name ='ALEX BROWN')
student30 = Student(student_id=30, school='Orange High School', grade_level=10, name ='RYAN HENDERSON')
student31 = Student(student_id=31, school='Eastern Alamance High School', grade_level=12, name ='HAO LIU')
student32 = Student(student_id=32, school='Orange High School', grade_level=10, name ='EVA CHAFFIN')
student33 = Student(student_id=33, school='Rockingham County High', grade_level=11, name ='ASTRID KOHLWES')
student34 = Student(student_id=34, school='Orange High School', grade_level=10, name ='AMY MCGOWEN')
student35 = Student(student_id=35, school='Rockingham County High', grade_level=12, name ='JOE WOLSTENCROFT PHD')
student36 = Student(student_id=36, school='Rockingham County High', grade_level=10, name ='MELISSA WHITE')
student37 = Student(student_id=37, school='Orange High School', grade_level=12, name ='MARTIN PALUCH')
student38 = Student(student_id=38, school='Orange High School', grade_level=9, name ='CHRIS TAYLOR')
student39 = Student(student_id=39, school='Rockingham County High', grade_level=10, name ='JEAN-SEBASTIEN LEGARE')
student40 = Student(student_id=40, school='Eastern Alamance High School', grade_level=11, name ='TCC LAST')
student41 = Student(student_id=41, school='Orange High School', grade_level=10, name ='ANTOINE MONSTIER')
student42 = Student(student_id=42, school='Eastern Alamance High School', grade_level=11, name ='GARY LORFANO')
student43 = Student(student_id=43, school='Eastern Alamance High School', grade_level=11, name ='MAT SHERWOOD')
student44 = Student(student_id=44, school='Orange High School', grade_level=11, name ='TIMOTHY RYKACZEWSKI')
student45 = Student(student_id=45, school='Orange High School', grade_level=10, name ='JORGE ARTETA')
student46 = Student(student_id=46, school='Rockingham County High', grade_level=12, name ='JENNA CRAVEN')
student47 = Student(student_id=47, school='Rockingham County High', grade_level=12, name ='YOLANDA JAKUBOWSKI')
student48 = Student(student_id=48, school='Orange High School', grade_level=10, name ='BOB BRANCATO')
student49 = Student(student_id=49, school='Rockingham County High', grade_level=12, name ='JANE GANNON')
student50 = Student(student_id=50, school='Orange High School', grade_level=12, name ='CRAIG HUNTER')
student51 = Student(student_id=51, school='Rockingham County High', grade_level=9, name ='TS BREYER')
student52 = Student(student_id=52, school='Rockingham County High', grade_level=12, name ='JOHN GARDNER')
student53 = Student(student_id=53, school='Orange High School', grade_level=11, name ='LISA DEPAULO')
student54 = Student(student_id=54, school='Orange High School', grade_level=10, name ='DAVID BROCK')
student55 = Student(student_id=55, school='Orange High School', grade_level=11, name ='DEAN LONDO')
student56 = Student(student_id=56, school='Rockingham County High', grade_level=9, name ='SEAN BUSCA')
student57 = Student(student_id=57, school='Orange High School', grade_level=12, name ='PETER MURPHY')
student58 = Student(student_id=58, school='Eastern Alamance High School', grade_level=11, name ='MARIETJIE DU PLESSIS')
student59 = Student(student_id=59, school='Rockingham County High', grade_level=9, name ='DANIEL ROONEY')
student60 = Student(student_id=60, school='Eastern Alamance High School', grade_level=12, name ='JASON DICK')
student61 = Student(student_id=61, school='Eastern Alamance High School', grade_level=10, name ='TA LAST')
student62 = Student(student_id=62, school='Eastern Alamance High School', grade_level=11, name ='RYAN PRITCHARD')
student63 = Student(student_id=63, school='Rockingham County High', grade_level=10, name ='ERIC SUKHENKO')
student64 = Student(student_id=64, school='Eastern Alamance High School', grade_level=9, name ='STEPHANIE CHIQUILLO')
student65 = Student(student_id=65, school='Orange High School', grade_level=10, name ='ROBERT DEVITZ')
student66 = Student(student_id=66, school='Eastern Alamance High School', grade_level=9, name ='TKC AIMES')
student67 = Student(student_id=67, school='Orange High School', grade_level=12, name ='JEAN FRANCOIS MARINIER')
student68 = Student(student_id=68, school='Rockingham County High', grade_level=10, name ='CHRIS HAGARTY')
student69 = Student(student_id=69, school='Orange High School', grade_level=9, name ='LYNN BLAKE')
student70 = Student(student_id=70, school='Orange High School', grade_level=12, name ='MIKE SMITH')
student71 = Student(student_id=71, school='Eastern Alamance High School', grade_level=12, name ='PATRICIA CAMERON')
student72 = Student(student_id=72, school='Rockingham County High', grade_level=9, name ='NICHOLAS ELLISON')
student73 = Student(student_id=73, school='Rockingham County High', grade_level=11, name ='MN GRAND')
student74 = Student(student_id=74, school='Orange High School', grade_level=9, name ='CAROL DISLER')
student75 = Student(student_id=75, school='Orange High School', grade_level=10, name ='RITA REASONS')
student76 = Student(student_id=76, school='Orange High School', grade_level=11, name ='HUAN NGUYEN')
student77 = Student(student_id=77, school='Orange High School', grade_level=12, name ='TATSURO OSHIMOTO')
student78 = Student(student_id=78, school='Orange High School', grade_level=10, name ='BARRY COLFLESH')
student79 = Student(student_id=79, school='Rockingham County High', grade_level=10, name ='CINDY CHACE')
student80 = Student(student_id=80, school='Rockingham County High', grade_level=9, name ='JOE FALARDEAU')
student81 = Student(student_id=81, school='Rockingham County High', grade_level=9, name ='MARCUS YADO')
student82 = Student(student_id=82, school='Rockingham County High', grade_level=10, name ='JEFF BABINEAU')
student83 = Student(student_id=83, school='Eastern Alamance High School', grade_level=9, name ='JIM WHELAN')
student84 = Student(student_id=84, school='Rockingham County High', grade_level=11, name ='JIM TONORE')
student85 = Student(student_id=85, school='Orange High School', grade_level=9, name ='ABBY CHEN')
student86 = Student(student_id=86, school='Rockingham County High', grade_level=11, name ='MANWAH HO')
student87 = Student(student_id=87, school='Eastern Alamance High School', grade_level=11, name ='RICK KELLY')
student88 = Student(student_id=88, school='Orange High School', grade_level=12, name ='SYLVAIN RABY')
student89 = Student(student_id=89, school='Rockingham County High', grade_level=10, name ='JEREMY CHEN')
student90 = Student(student_id=90, school='Rockingham County High', grade_level=10, name ='DEBRA COTELA')
student91 = Student(student_id=91, school='Rockingham County High', grade_level=12, name ='PR LAST')
student92 = Student(student_id=92, school='Rockingham County High', grade_level=11, name ='RICHARD MAYCHRICH')
student93 = Student(student_id=93, school='Orange High School', grade_level=10, name ='ANNA BROWE')
student94 = Student(student_id=94, school='Orange High School', grade_level=9, name ='JACLYN BEAUDREAU - CUMMINGS')
student95 = Student(student_id=95, school='Eastern Alamance High School', grade_level=11, name ='DUSTIN RALSTON')
student96 = Student(student_id=96, school='Eastern Alamance High School', grade_level=12, name ='CATHY CURTIS-WHITE')
student97 = Student(student_id=97, school='Eastern Alamance High School', grade_level=12, name ='DICK SHURTS')
student98 = Student(student_id=98, school='Rockingham County High', grade_level=12, name ='JOHN REHUS')
student99 = Student(student_id=99, school='Orange High School', grade_level=12, name ='BEN JAMES')
student100 = Student(student_id=100, school='Rockingham County High', grade_level=11, name ='ANDREW SZUNYOG')
student101 = Student(student_id=101, school='Eastern Alamance High School', grade_level=11, name ='DANIEL DIAS')
student102 = Student(student_id=102, school='Eastern Alamance High School', grade_level=12, name ='PETER SMITH')
student103 = Student(student_id=103, school='Rockingham County High', grade_level=11, name ='RICK BURR')
student104 = Student(student_id=104, school='Rockingham County High', grade_level=9, name ='GREGORY RICHARDSON')
student105 = Student(student_id=105, school='Rockingham County High', grade_level=10, name ='MAXIME POUCHET')
student106 = Student(student_id=106, school='Orange High School', grade_level=12, name ='MICHAEL ABRAHAM')
student107 = Student(student_id=107, school='Orange High School', grade_level=12, name ='CHARLES ZHANG')
student108 = Student(student_id=108, school='Rockingham County High', grade_level=9, name ='ANDREW TOBEY')
student109 = Student(student_id=109, school='Eastern Alamance High School', grade_level=10, name ='PAIGE PEREZ')
student110 = Student(student_id=110, school='Rockingham County High', grade_level=11, name ='JESSICA MIREAULT')
student111 = Student(student_id=111, school='Rockingham County High', grade_level=12, name ='VAL PATARINI')
student112 = Student(student_id=112, school='Rockingham County High', grade_level=10, name ='HEBE CONG')
student113 = Student(student_id=113, school='Rockingham County High', grade_level=9, name ='FUYUKA TSURUDA')
student114 = Student(student_id=114, school='Rockingham County High', grade_level=12, name ='JAMES HARRIS')
student115 = Student(student_id=115, school='Orange High School', grade_level=9, name ='JOHN C. HAMMER')
student116 = Student(student_id=116, school='Eastern Alamance High School', grade_level=10, name ='PETER SMITH')